trigger:
- main

pool:
  name: sub

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest
  displayName: 'Run tests'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'my-azure-subscription'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
      az storage blob upload-batch -d $(AZURE_CONTAINER_NAME) -s processed/
  displayName: 'Deploy to Azure'